### ISSUE TITLE
pyats create testbed netbox issue

### ISSUE THREAD

**Issue by Simperdy** [CiscoTestAutomation/pyats.contrib#32]
Hello,

I hope this is the right place for my issue.
I have an issue while creating a testbed file from netbox.
Netbox version: v2.11.2

Steps:
1. create new folder and cd into it
2. create venv and activate
3. pip install "pyats[full]" and pip install pyats.contrib (Requirements already satisfied by "pyats[full]", I guess)
4. cd bin
5. pyats create testbed netbox --output testbed.yaml --netbox-url=https://netbox.domain.com --user-token=XXX

Output:
`Begin retrieving data from netbox...

'NoneType' object is not iterable`

I had more arguments in the begining and reduced the arguments to the required ones.
I get the same error everytime.

Any ideas what I'm doing wrong or is this a bug?

**Comment by tahigash** [comment]
Hi Simperdy,

hard to guess what the issue is based on info. can you try the `pyats create testbed netbox` command with `-v`. and share what you see. of course, please hide url/token when you share.

example:
```
pyats create testbed netbox --output testbed.yaml --netbox-url=<url> --user-token=<token> -v
Begin retrieving data from netbox...
Starting new HTTP connection (1): <url>:80
http://<url>:80 "GET /api/dcim/devices/?format=json HTTP/1.1" 200 2883
Starting new HTTP connection (1): <url>:80
http://<url>:80 "GET /api/virtualization/virtual-machines/?format=json HTTP/1.1" 200 52
Retrieving associated data for dc-access1...
(snip)
```
if you can do `pdb` and trace when the error happens in python code, it would be helpful.

**Comment by Simperdy** [comment]
Hi tahigash,

sure, here is the output with the -v command.

```
➜  pyats_v2 source bin/activate
(pyats_v2) ➜  pyats_v2 bin/pyats create testbed netbox --output testbed.yaml --netbox-url="https://netbox.domain.com" --user-token="XXX" -v
Begin retrieving data from netbox...
Starting new HTTPS connection (1): netbox.domain.com:443
Traceback (most recent call last):
  File "src/pyats/cli/base.py", line 207, in pyats.cli.base.Command.main
  File "src/pyats/cli/base.py", line 337, in pyats.cli.base.CommandWithSubcommands.run
  File "src/genie/cli/commands/create_testbed.py", line 34, in genie.cli.commands.create_testbed.CreateTestbed.run
  File "/home/user/git/network/pyats_v2/lib/python3.8/site-packages/pyats/contrib/creators/creator.py", line 208, in to_testbed_file
    testbed = self._generate()
  File "/home/user/git/network/pyats_v2/lib/python3.8/site-packages/pyats/contrib/creators/netbox.py", line 542, in _generate
    response += self._get_request(devices_url, headers, "results")
TypeError: 'NoneType' object is not iterable


'NoneType' object is not iterable
```

I'm not very familiar with the python debugger, but I tried the following.

```
#!/usr/bin/env python

from pyats.contrib.creators.netbox import Netbox

nb_testbed = Netbox (
    netbox_url="https://netbox.domain.com",
    user_token="XXX"
)
import pdb; pdb.set_trace()
tb = nb_testbed._generate()
```

on execute I tried to move to the failure with "s" and "n".

```
(Pdb) 
--Call--
> /usr/lib/python3.8/codecs.py(319)decode()
-> def decode(self, input, final=False):
(Pdb) 
> /usr/lib/python3.8/codecs.py(321)decode()
-> data = self.buffer + input
(Pdb) 
> /usr/lib/python3.8/codecs.py(322)decode()
-> (result, consumed) = self._buffer_decode(data, self.errors, final)
(Pdb) 
> /usr/lib/python3.8/codecs.py(324)decode()
-> self.buffer = data[consumed:]
(Pdb) 
> /usr/lib/python3.8/codecs.py(325)decode()
-> return result
(Pdb) 
--Return--
> /usr/lib/python3.8/codecs.py(325)decode()->'lter is None...          log'
-> return result
```

Let me know if you need more info.

**Comment by tahigash** [comment]
@Simperdy thanks for the info and debug. It looks like we need to check the response from server. 
Your url is `https`. certificate can be verified? if not, please try with `--verify=False` like below:
```
pyats create testbed netbox --output testbed.yaml --netbox-url=<url> --user-token=<token> --verify=False -v
```
even if above doesn't work, please check if you can get response properly without pyATS by `curl` command.

```
curl -H "Authorization: Token <token>" -H "Accept: application/json; indent=4" <url> -v

**Comment by Simperdy** [comment]
@tahigash the Netbox API already works with other software. We use a selfsigned certificate from our corporate CA which is present on my device.

Output from the --verify command.
```
(pyats_v2) ➜  pyats_v2 bin/pyats create testbed netbox --output testbed.yaml --netbox-url="https://netbox.domain.com" --user-token="XXX" --verify=False -v
Begin retrieving data from netbox...
Traceback (most recent call last):
  File "src/pyats/cli/base.py", line 207, in pyats.cli.base.Command.main
  File "src/pyats/cli/base.py", line 337, in pyats.cli.base.CommandWithSubcommands.run
  File "src/genie/cli/commands/create_testbed.py", line 34, in genie.cli.commands.create_testbed.CreateTestbed.run
  File "/home/user/git/network/pyats_v2/lib/python3.8/site-packages/pyats/contrib/creators/creator.py", line 208, in to_testbed_file
    testbed = self._generate()
  File "/home/user/git/network/pyats_v2/lib/python3.8/site-packages/pyats/contrib/creators/netbox.py", line 542, in _generate
    response += self._get_request(devices_url, headers, "results")
TypeError: 'NoneType' object is not iterable


'NoneType' object is not iterable
```

Output from curl without pyATS:
```
(pyats_v2) ➜  pyats_v2 curl -H "Authorization: Token <XXX>" -H "Accept: application/json; indent=4" https://netbox.domain.com/api/dcim/sites/ -v
*   Trying XXX.XXX.XXX.XXX:443...
* TCP_NODELAY set
* Connected to netbox.domain.com (XXX.XXX.XXX.XXX) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=Country; ST=State; L=City; street=street; postalCode=XXXX; O=Company
*  start date: Apr 29 14:49:57 2021 GMT
*  expire date: Jul 28 14:50:27 2021 GMT
*  subjectAltName: host "netbox.domain.com" matched cert's "netbox.domain.com"
*  issuer: C=Country; ST=State; L=City; O=Company; OU=OU; CN=XXX
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55841efaaea0)
> GET /api/dcim/sites/ HTTP/2
> Host: netbox.domain.com
> user-agent: curl/7.68.0
> authorization: Token XXXXXX
> accept: application/json; indent=4
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 200 
< content-type: application/json
< vary: Accept, Cookie, Origin
< allow: GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS
< api-version: 2.11
< x-content-type-options: nosniff
< referrer-policy: same-origin
< x-frame-options: SAMEORIGIN
< content-length: 21250
< server: Unit/1.22.0
< date: Fri, 07 May 2021 10:39:13 GMT
< strict-transport-security: max-age=31536000; includeSubDomains
< 
{
    "count": 13,
    "next": null,
    "previous": null,
    "results": [

deleted the results for this post, but I see all 13 sites as result

               ]
* Connection #0 to host netbox.domain.com left intact
}%
```

doesn't look like a https issue to me.

**Comment by tahigash** [comment]
@Simperdy thanks for the checks. OK. no issue with certificate. This is hard to troubleshoot from here without reproducible setup. can you create same condition by using netbox docker or can you provide steps to reproduce? I need to debug on my side, but I cannot reproduce the issue.

**Comment by tahigash** [comment]
@Simperdy , thanks for detailed response. and glad to hear you resolved the issue. We will see if we can enhance the messages.
