### ISSUE TITLE
Testbed File Creator fails with paths including "-"

### ISSUE THREAD

**Issue by hpreston** [CiscoTestAutomation/pyats.contrib#33]
Ran into an error when trying to create a testbed from a file with this command 

```
pyats create testbed file --path nso-sandbox-devices.xlsx --output nso-sandbox-testbed.yaml -vvv    
```

The error at was 

```
Traceback (most recent call last):
  File "src/pyats/cli/base.py", line 207, in pyats.cli.base.Command.main
  File "src/pyats/cli/base.py", line 337, in pyats.cli.base.CommandWithSubcommands.run
  File "src/genie/cli/commands/create_testbed.py", line 34, in genie.cli.commands.create_testbed.CreateTestbed.run
  File "/Users/hpreston/virtualenvs/std/lib/python3.8/site-packages/pyats/contrib/creators/file.py", line 68, in to_testbed_file
    testbed = self._generate()
  File "/Users/hpreston/virtualenvs/std/lib/python3.8/site-packages/pyats/contrib/creators/file.py", line 124, in _generate
    devices = self._read_device_data(self._path)
  File "/Users/hpreston/virtualenvs/std/lib/python3.8/site-packages/pyats/contrib/creators/file.py", line 139, in _read_device_data
    _, extension = os.path.splitext(file)
  File "/usr/local/Cellar/python@3.8/3.8.9/bin/../Frameworks/Python.framework/Versions/3.8/lib/python3.8/posixpath.py", line 118, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not bool

expected str, bytes or os.PathLike object, not bool
```

Changing the file names to use underscores instead of dashes worked no problem. 

```
pyats create testbed file --path nso_sandbox_devices.xlsx --output nso_sandbox_testbed.yaml -vvv

Testbed file generated: 
nso_sandbox_devices.xlsx -> nso_sandbox_testbed.yaml
```

While python generally prefers underscores to dashes, this seems like a bad restriction on the creation utility.  Furthermore, a much better error would be nice to the user.

**Comment by LukasMcClelland** [comment]
Hi Hank, 

Thank for letting us know about this issue. Agreed; not the best restriction!

Assigning Takashi to help you out with this.

**Comment by tahigash** [comment]
@hpreston opened above PR with fix. now under review.
